site_title: Lambert RCR
site_slogan: Les premiers soins biens équipés
site_description: >-
  Lambert RCR est une entreprise de matériel de premiers soins, qui offre
  également des formations aux services de gardes et CPEs adaptés pour les gens
  en milieux de gardes.  



  Nous offrons aussi sur demande des cours de RCR/DEA de la fondation des
  Maladies du coeur et de l’AVC canadienne. Nous pouvons nous déplacer chez vous
  pour un groupe de 8 à 12 participants.
site_image: /img/rcr-premiers-soins-cover-image.jpg
site_email: lambertrcr@gmail.com
site_tel: (450) 974-0972
url_facebook: 'https://www.facebook.com/lambertRCR/'
url_instagram: 'http://www.thepictaram.club/instagram/lambertrcr'
