site_title: Lambert RCR
site_slogan: Les premiers soins biens équipés
site_description: >-
  Nous offrons une gamme complète de cours de premiers soins et réanimation
  cardio-respiratoire pour toutes sortes de besoins.


  Nous opérons à Laval et la rive nord de Montréal (Boisbriand, Saint-Eustache,
  Bois-des-fillions,Sainte-Thérèse, Rosemère, Deux-montagnes, Terrebonne,
  Mascouche, Blainville etc).

   Nos groupes sont ouverts à tous. Nos cours de premiers soins en milieux de garde sont conformes aux demandes du ministère de la famille et des ainés.
site_head: >-
  <meta name="google-site-verification"
  content="D4b8sg45A7zsXUSLD-w7FXL-GYGx0SOpKZB4SFlKDqw" />

  <meta name="msvalidate.01" content="A62CB6AA1DC4D9C07DD78F3C4C16A631" />

  <!-- Facebook Pixel Code -->

  <script>

  !function(f,b,e,v,n,t,s)   {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};
  if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
  n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];
  s.parentNode.insertBefore(t,s)}(window, document,'script',
  'https://connect.facebook.net/en_US/fbevents.js');   fbq('init',
  '880240528822735');   fbq('track', 'PageView'); </script> <noscript><img
  height="1" width="1" style="display:none"
  src="https://www.facebook.com/tr?id=880240528822735&ev=PageView&noscript=1" />

  </noscript>

  <!-- End Facebook Pixel Code -->

  <style>.async-hide { opacity: 0 !important} </style>

  <script>(function(a,s,y,n,c,h,i,d,e){s.className+=' '+y;h.start=1*new Date;

  h.end=i=function(){s.className=s.className.replace(RegExp(' ?'+y),'')};

  (a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c;

  })(window,document.documentElement,'async-hide','dataLayer',4000,

  {'GTM-WMGR45D':true});</script>


  <meta name="google-site-verification"
  content="gmincYH1G8iw_VaJNLBegkjMMcKSUVb-MOkeWeqnZw0" />





  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-107295384-2', 'auto');
    ga('require', 'GTM-WMGR45D');
    ga('send', 'pageview');
  </script>
site_image: /img/lambert-rcr-cover.jpg
site_email: lambertrcr@gmail.com
site_tel: (450) 974-0972
url_facebook: 'https://www.facebook.com/lambertRCR/'
url_instagram: 'https://www.instagram.com/lambertrcr/'
