site_title: Lambert RCR
site_slogan: Les premiers soins biens équipés
site_description: >-
  Nous offrons une gamme complète de cours de premiers soins et réanimation
  cardio-respiratoire pour toutes sortes de besoins. Nous opérons à Laval et la
  rive nord de Montréal (Boisbriand, Saint-Eustache,
  Bois-des-fillions,Sainte-Thérèse, Rosemère, Deux-montagnes, Terrebonne,
  Mascouche, Blainville etc). Nos groupes sont ouverts à tous. Nos cours de
  premiers soins en milieux de garde sont conformes aux demandes du ministère de
  la famille et des ainés
site_image: /img/rcr-premiers-soins-cover-image.jpg
site_email: lambertrcr@gmail.com
site_tel: (450) 974-0972
url_facebook: 'https://www.facebook.com/lambertRCR/'
url_instagram: 'https://www.instagram.com/lambertrcr/'
