site_title: Lambert RCR
site_slogan: Les premiers soins biens équipés
site_image: /img/rcr-premiers-soins-cover-image.jpg
site_email: lambertrcr@gmail.com
site_tel: (450) 974-0972
url_facebook: 'https://www.facebook.com/lambertRCR/'
