backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "img"

collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "homepage"
    label: "Page d'accueil"
    files:
      - file: "index.md"
        label: "Éditer la page d'accueil"
        name: "home"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/" }
          - {label: "Slideshow", name: slideshow, widget: object, required: false,
              fields: [{label: Image, name: slideshow-images, widget: list, required: false,
                  fields: [{label: Image, name: image, widget: image}, {label: Title, name: title, widget: string}
                  ]
              }]
            }
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "navigation" # Used in routes, e.g., /admin/collections/blog
    label: "Navigation" # Used in the UI
    folder: "_nav" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - name: title
        label: Title
        widget: relation
        collection: pages
        searchFields: [title]
        valueField: title
      - name: slug
        label: Link
        widget: relation
        collection: pages
        searchFields: [permalink]
        valueField: permalink
      - {label: "Order", name: "order", widget: "number"}

  - name: "formations" # Used in routes, e.g., /admin/collections/blog
    label: "Formations" # Used in the UI
    folder: "_formations" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Durée", name: "duree", widget: "string", required: false}
      - {label: "Prix", name: "prix", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "markdown"}
