backend:

  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "img"

collections:

  - name: "special-pages"
    label: "Pages uniques"
    delete: false # Prevent users from deleting documents in this collection
    files:
      - name: "home"
        file: "index.md"
        label: "Éditer la page d'accueil"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden", default: "/" }
          - {label: "Description", name: "description", widget: "string" }
          - label: "Slideshow"
            name: slideshow
            widget: object
            required: false
            fields:
              - label: Image
                name: slideshow-images
                widget: list
                required: false
                fields:
                  - {label: Image, name: image, widget: image}
                  - {label: Title, name: title, widget: string}
          - {label: "Contenu", name: "body", widget: "markdown"}

      - name: "formation-page"
        file: "formations.md"
        label: "Éditer la page des formations"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "formation"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string", default: "/formations" }
          - {label: "Description", name: "description", widget: "string" }
          - {label: "Contenu", name: "body", widget: "markdown"}

      - name: "materiel-page"
        file: "materiel.md"
        label: "Éditer la page de vente des matériels"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "materiel"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string", default: "/materiels-de-premiers-soins" }
          - {label: "Description", name: "description", widget: "string" }
          - {label: "Contenu", name: "body", widget: "markdown"}

  - name: "settings"
    label: "Paramètres du site"
    delete: false # Prevent users from deleting documents in this collection
    editor:
     preview: false
    files:
       - name: "general"
         label: "Général"
         file: "_data/settings.json"
         description: "Paramètres Généraux"
         fields:
           - {label: "Titre du site", name: "site_title", widget: "string"}
           - {label: "Slogan du site", name: "site_slogan", widget: "string"}

       - name: "navigation"
         label: "Navigation"
         file: "_data/navigation.json"
         description: "Navigation du site"
         fields:
          - label: "Navigation principale"
            name: main_nav
            widget: object
            fields:
              - label: Link
                name: links
                widget: list
                required: false
                fields:
                  - {label: Titre, name: title, widget: string}
                  - {label: URL, name: url, widget: string}

  - name: "formation-dates"
    label: "Dates de cours"
    delete: false # Prevent users from deleting documents in this collection
    editor:
     preview: false
    files:
      - name: "inscription-page"
        file: "inscription.md"
        label: "Éditer la page des inscriptions"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "inscription"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string", default: "/inscription" }
          - {label: "Description", name: "description", widget: "string" }
          - {label: "Contenu", name: "body", widget: "markdown"}

      - name: "dates-de-cours"
        label: "Éditer les dates de cours"
        file: "_data/dates.json"
        description: "Éditer les dates de cours"
        fields:
          - label: "Dates de formation"
            name: dates_de_cours
            widget: object
            fields:
              - label: Formation
                name: cours
                widget: list
                fields:
                  - name: title
                    label: Titre de la formation
                    widget: relation
                    collection: formations
                    searchFields: [title]
                    valueField: title
                  - label: Date
                    name: date
                    widget: string
                    fields:
                      - {label: ID, name: date-id, widget: "hidden", default: "1"}
                      - {label: Date, name: date-item, widget: "string"}

  - name: "formations" # Used in routes, e.g., /admin/collections/blog
    label: "Formations" # Used in the UI
    folder: "_formations" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "formation-page"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Ordre", name: "order", widget: "number", default: "1"}
      - {label: "Lien", name: "permalink", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Durée", name: "duration", widget: "string", required: false}
      - {label: "Prix", name: "price", widget: "string", required: false}
      - {label: "Certification", name: "certification", widget: "string", required: false}
      - {label: "Contenu", name: "body", widget: "markdown"}

  - name: "materiel" # Used in routes, e.g., /admin/collections/blog
    label: "Matériel de premiers soins" # Used in the UI
    folder: "_materiel" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Lien", name: "permalink", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Prix", name: "price", widget: "string"}


  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Lien", name: "permalink", widget: "string"}
      - {label: "Description", name: "description", widget: "string" }
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Contenu", name: "body", widget: "markdown"}
